In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [4]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [5]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\HT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9527777777777777

In [6]:
rf = RandomForestClassifier(n_estimators=35,criterion='entropy')
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9694444444444444

Using K-Fold Validation

In [7]:
from sklearn.model_selection import KFold

In [8]:
k_fold = KFold(n_splits=3)
k_fold

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train, test in k_fold.split([1,2,3,4,5,6,7,8,9,10]):
    print(train,test)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [11]:
get_score(LogisticRegression(max_iter=1000000),X_train,X_test,y_train,y_test)

0.9527777777777777

Now Using StratifiedKFold

In [12]:
from sklearn.model_selection import StratifiedKFold

In [13]:
folds = StratifiedKFold(n_splits=3)

In [14]:
score_lr = np.array([])
score_svm = np.array([])
score_rf = np.array([])

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_lr = np.append(score_lr,get_score(LogisticRegression(max_iter=10000), X_train, X_test,y_train,y_test))
    score_svm = np.append(score_svm,get_score(svm, X_train, X_test,y_train,y_test))
    score_rf = np.append(score_rf,get_score(rf, X_train, X_test,y_train,y_test))
    

In [15]:
score_lr.mean()

np.float64(0.9259877573734001)

In [16]:
score_rf.mean()

np.float64(0.9343350027824151)

In [17]:
score_svm.mean()

np.float64(0.9699499165275459)

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(rf,digits.data,digits.target).mean()

np.float64(0.9376988548437015)

In [20]:
cross_val_score(RandomForestClassifier(n_estimators=35, criterion='entropy'),digits.data,digits.target).mean()

np.float64(0.9349102445063447)

Exercise

In [22]:
from sklearn.datasets import load_iris

In [24]:
iris = load_iris()

In [25]:
cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target,cv=StratifiedKFold())

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [26]:
cross_val_score(SVC(), iris.data, iris.target,cv=StratifiedKFold())

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [27]:
cross_val_score(RandomForestClassifier(n_estimators=35), iris.data, iris.target,cv=StratifiedKFold())

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])